import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Hero from "../components/Home/Hero";
import Axis from "../components/Home/Axis";
import TimeLine from "../components/Home/TimeLine";
import Projects from "../components/Home/Projects";
import ContactUs from "../components/Home/ContactUs";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={" leading-normal tracking-normal text-white gradient"}>
        <Hero />
        <Axis />
        <TimeLine />
        <Projects />
        <ContactUs />
        {/* <!-- Change the colour #f8fafc to match the previous section colour --> */}
      </main>
    </>
  );
}
